// automatically generated by the FlatBuffers compiler, do not modify

package fr.kissy.zergling_push.event;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerLeaved extends Table {
  public static PlayerLeaved getRootAsPlayerLeaved(ByteBuffer _bb) { return getRootAsPlayerLeaved(_bb, new PlayerLeaved()); }
  public static PlayerLeaved getRootAsPlayerLeaved(ByteBuffer _bb, PlayerLeaved obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean PlayerLeavedBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "PLLV"); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayerLeaved __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createPlayerLeaved(FlatBufferBuilder builder,
      int idOffset) {
    builder.startObject(1);
    PlayerLeaved.addId(builder, idOffset);
    return PlayerLeaved.endPlayerLeaved(builder);
  }

  public static void startPlayerLeaved(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static int endPlayerLeaved(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPlayerLeavedBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "PLLV"); }
}

