// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.PlayerLeaved = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.PlayerLeaved}
 */
fr.kissy.zergling_push.event.PlayerLeaved.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.PlayerLeaved=} obj
 * @returns {fr.kissy.zergling_push.event.PlayerLeaved}
 */
fr.kissy.zergling_push.event.PlayerLeaved.getRootAsPlayerLeaved = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.PlayerLeaved).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.PlayerLeaved.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PLLV');
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fr.kissy.zergling_push.event.PlayerLeaved.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.PlayerLeaved.startPlayerLeaved = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fr.kissy.zergling_push.event.PlayerLeaved.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.PlayerLeaved.endPlayerLeaved = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.PlayerLeaved.finishPlayerLeavedBuffer = function(builder, offset) {
  builder.finish(offset, 'PLLV');
};

// Exports for Node.js and RequireJS
this.fr = fr;
