// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.PlayerHit = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.PlayerHit}
 */
fr.kissy.zergling_push.event.PlayerHit.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.PlayerHit=} obj
 * @returns {fr.kissy.zergling_push.event.PlayerHit}
 */
fr.kissy.zergling_push.event.PlayerHit.getRootAsPlayerHit = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.PlayerHit).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.PlayerHit.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PLHT');
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fr.kissy.zergling_push.event.PlayerHit.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerHit.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fr.kissy.zergling_push.event.PlayerHit.prototype.shot = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.PlayerHit.startPlayerHit = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fr.kissy.zergling_push.event.PlayerHit.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
fr.kissy.zergling_push.event.PlayerHit.addTime = function(builder, time) {
  builder.addFieldInt32(1, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} shotOffset
 */
fr.kissy.zergling_push.event.PlayerHit.addShot = function(builder, shotOffset) {
  builder.addFieldOffset(2, shotOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.PlayerHit.endPlayerHit = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.PlayerHit.finishPlayerHitBuffer = function(builder, offset) {
  builder.finish(offset, 'PLHT');
};

// Exports for Node.js and RequireJS
this.fr = fr;
