// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.PlayerMoved = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.PlayerMoved}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.PlayerMoved=} obj
 * @returns {fr.kissy.zergling_push.event.PlayerMoved}
 */
fr.kissy.zergling_push.event.PlayerMoved.getRootAsPlayerMoved = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.PlayerMoved).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.PlayerMoved.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PLMV');
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.duration = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.sequence = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.velocity = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.angularVelocity = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.PlayerMoved.prototype.firing = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.PlayerMoved.startPlayerMoved = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fr.kissy.zergling_push.event.PlayerMoved.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
fr.kissy.zergling_push.event.PlayerMoved.addTime = function(builder, time) {
  builder.addFieldInt32(1, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} duration
 */
fr.kissy.zergling_push.event.PlayerMoved.addDuration = function(builder, duration) {
  builder.addFieldFloat32(2, duration, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequence
 */
fr.kissy.zergling_push.event.PlayerMoved.addSequence = function(builder, sequence) {
  builder.addFieldInt32(3, sequence, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} velocity
 */
fr.kissy.zergling_push.event.PlayerMoved.addVelocity = function(builder, velocity) {
  builder.addFieldInt8(4, velocity, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} angularVelocity
 */
fr.kissy.zergling_push.event.PlayerMoved.addAngularVelocity = function(builder, angularVelocity) {
  builder.addFieldInt8(5, angularVelocity, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} firing
 */
fr.kissy.zergling_push.event.PlayerMoved.addFiring = function(builder, firing) {
  builder.addFieldInt8(6, +firing, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.PlayerMoved.endPlayerMoved = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.PlayerMoved.finishPlayerMovedBuffer = function(builder, offset) {
  builder.finish(offset, 'PLMV');
};

// Exports for Node.js and RequireJS
this.fr = fr;
