// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.PlayerSnapshot = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.PlayerSnapshot}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.PlayerSnapshot=} obj
 * @returns {fr.kissy.zergling_push.event.PlayerSnapshot}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.getRootAsPlayerSnapshot = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.PlayerSnapshot).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PLSP');
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.sequence = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.prototype.shields = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.PlayerSnapshot.startPlayerSnapshot = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequence
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addSequence = function(builder, sequence) {
  builder.addFieldInt32(1, sequence, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addX = function(builder, x) {
  builder.addFieldFloat32(2, x, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addY = function(builder, y) {
  builder.addFieldFloat32(3, y, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(4, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} shields
 */
fr.kissy.zergling_push.event.PlayerSnapshot.addShields = function(builder, shields) {
  builder.addFieldInt8(5, shields, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.PlayerSnapshot.endPlayerSnapshot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.PlayerSnapshot.finishPlayerSnapshotBuffer = function(builder, offset) {
  builder.finish(offset, 'PLSP');
};

// Exports for Node.js and RequireJS
this.fr = fr;
