// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Event = Event || {};

/**
 * @constructor
 */
Event.ProjectileSnapshot = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Event.ProjectileSnapshot}
 */
Event.ProjectileSnapshot.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Event.ProjectileSnapshot=} obj
 * @returns {Event.ProjectileSnapshot}
 */
Event.ProjectileSnapshot.getRootAsProjectileSnapshot = function(bb, obj) {
  return (obj || new Event.ProjectileSnapshot).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
Event.ProjectileSnapshot.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('PJSP');
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Event.ProjectileSnapshot.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
Event.ProjectileSnapshot.prototype.x = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
Event.ProjectileSnapshot.prototype.y = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
Event.ProjectileSnapshot.prototype.rotation = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
Event.ProjectileSnapshot.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Event.ProjectileSnapshot.startProjectileSnapshot = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
Event.ProjectileSnapshot.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 */
Event.ProjectileSnapshot.addX = function(builder, x) {
  builder.addFieldFloat32(1, x, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} y
 */
Event.ProjectileSnapshot.addY = function(builder, y) {
  builder.addFieldFloat32(2, y, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} rotation
 */
Event.ProjectileSnapshot.addRotation = function(builder, rotation) {
  builder.addFieldFloat32(3, rotation, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
Event.ProjectileSnapshot.addTime = function(builder, time) {
  builder.addFieldInt32(4, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Event.ProjectileSnapshot.endProjectileSnapshot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Event.ProjectileSnapshot.finishProjectileSnapshotBuffer = function(builder, offset) {
  builder.finish(offset, 'PJSP');
};

// Exports for Node.js and RequireJS
this.Event = Event;
