// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.TimeSyncRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.TimeSyncRequest}
 */
fr.kissy.zergling_push.event.TimeSyncRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.TimeSyncRequest=} obj
 * @returns {fr.kissy.zergling_push.event.TimeSyncRequest}
 */
fr.kissy.zergling_push.event.TimeSyncRequest.getRootAsTimeSyncRequest = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.TimeSyncRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.TimeSyncRequest.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('TSRQ');
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.TimeSyncRequest.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.TimeSyncRequest.startTimeSyncRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
fr.kissy.zergling_push.event.TimeSyncRequest.addTime = function(builder, time) {
  builder.addFieldInt32(0, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.TimeSyncRequest.endTimeSyncRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.TimeSyncRequest.finishTimeSyncRequestBuffer = function(builder, offset) {
  builder.finish(offset, 'TSRQ');
};

// Exports for Node.js and RequireJS
this.fr = fr;
