// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var fr = fr || {};

/**
 * @const
 * @namespace
 */
fr.kissy = fr.kissy || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push = fr.kissy.zergling_push || {};

/**
 * @const
 * @namespace
 */
fr.kissy.zergling_push.event = fr.kissy.zergling_push.event || {};

/**
 * @constructor
 */
fr.kissy.zergling_push.event.TimeSyncResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fr.kissy.zergling_push.event.TimeSyncResponse}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fr.kissy.zergling_push.event.TimeSyncResponse=} obj
 * @returns {fr.kissy.zergling_push.event.TimeSyncResponse}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.getRootAsTimeSyncResponse = function(bb, obj) {
  return (obj || new fr.kissy.zergling_push.event.TimeSyncResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('TSRS');
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.prototype.serverTime = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.prototype.serverStartTime = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fr.kissy.zergling_push.event.TimeSyncResponse.startTimeSyncResponse = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
fr.kissy.zergling_push.event.TimeSyncResponse.addTime = function(builder, time) {
  builder.addFieldInt32(0, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serverTime
 */
fr.kissy.zergling_push.event.TimeSyncResponse.addServerTime = function(builder, serverTime) {
  builder.addFieldInt32(1, serverTime, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} serverStartTime
 */
fr.kissy.zergling_push.event.TimeSyncResponse.addServerStartTime = function(builder, serverStartTime) {
  builder.addFieldInt32(2, serverStartTime, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fr.kissy.zergling_push.event.TimeSyncResponse.endTimeSyncResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fr.kissy.zergling_push.event.TimeSyncResponse.finishTimeSyncResponseBuffer = function(builder, offset) {
  builder.finish(offset, 'TSRS');
};

// Exports for Node.js and RequireJS
this.fr = fr;
